[package]
name = "ally"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ally-lib = { path = "../ally-lib" }
yaml-rust = "0.4.5"
clap = "3.1.6"
